"""README command paths must exist in the repository.

ADV2-2/ADV2-1 class of defect: documentation whose first copy-pasted command
fails with ``contract file not found``. A README command pointing at a path
the repo does not contain is a broken promise, so it is a test failure.

Rules:
- Every ``--contract <path>`` argument in a README code block must resolve to
  a file in the repo (contracts are committed, never generated).
- Every ``--runs <path>`` argument must resolve too, EXCEPT inside a code
  block that runs ``convert_inspect_log.py``: those blocks document converting
  a user's own log into a recording, so the recording is generated by the
  command above it and cannot be committed.

Fault detected: README quickstart containing
``agenteval run --contract contracts/research.yaml`` where that file does not
exist (ADV2-1) => this test fails.
"""

from __future__ import annotations

import os
import re
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

REPO_ROOT = os.path.join(os.path.dirname(__file__), "..")
README = os.path.join(REPO_ROOT, "README.md")

_BLOCK_RE = re.compile(r"```[a-z]*\n(.*?)```", re.DOTALL)
_CONTRACT_RE = re.compile(r"--contract\s+(\S+)")
_RUNS_RE = re.compile(r"--runs\s+(\S+)")


def _code_blocks() -> list[str]:
    with open(README, encoding="utf-8") as fh:
        return _BLOCK_RE.findall(fh.read())


def _contract_targets() -> list[tuple[str, str]]:
    """(block_index, path) for every --contract argument in the README."""
    out: list[tuple[str, str]] = []
    for i, block in enumerate(_code_blocks()):
        for path in _CONTRACT_RE.findall(block):
            out.append((f"block {i}", path))
    return out


def _runs_targets() -> list[tuple[str, str]]:
    """(block_index, path) for --runs args outside converter blocks."""
    out: list[tuple[str, str]] = []
    for i, block in enumerate(_code_blocks()):
        if "convert_inspect_log.py" in block:
            continue
        for path in _RUNS_RE.findall(block):
            out.append((f"block {i}", path))
    return out


class TestReadmeCommandPaths:
    def test_every_contract_path_exists(self) -> None:
        """Fault detected: README points --contract at a non-existent file."""
        targets = _contract_targets()
        assert targets, "README should document at least one --contract command"
        missing = [
            f"{where}: {path}"
            for where, path in targets
            if not os.path.isfile(os.path.join(REPO_ROOT, path))
        ]
        assert not missing, "README --contract paths do not exist in the repo: " + "; ".join(
            missing
        )

    def test_every_runs_path_exists(self) -> None:
        """Fault detected: README points --runs at a non-existent recording."""
        missing = [
            f"{where}: {path}"
            for where, path in _runs_targets()
            if not os.path.isfile(os.path.join(REPO_ROOT, path))
        ]
        assert not missing, "README --runs paths do not exist in the repo: " + "; ".join(missing)

    @pytest.mark.parametrize("where,path", _contract_targets())
    def test_contract_paths_parametrised(self, where: str, path: str) -> None:
        """Same check as above, parametrised so each path reports separately."""
        assert os.path.isfile(os.path.join(REPO_ROOT, path)), f"{where}: {path} missing"
